services:
  api:
    build: .
    container_name: market-risk-api

    ports:
      - "8000:8000"

    environment:
      DB_USER: ${API_DB_USER}
      DB_PASSWORD: ${API_DB_PASSWORD}
      DB_HOST: ${API_DB_HOST}
      DB_PORT: ${API_DB_PORT}
      DB_NAME: ${API_DB_NAME}
      UPDATE_API_KEY: ${UPDATE_API_KEY}



